/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.java.lessons;

/**
 *
 * To start the application:
 * ./gradlew build
 * java -jar ./L01-gradle/build/libs/gradleHelloWorld-0.1.jar
 *
 * To unzip the jar:
 * unzip -l L01-gradle.jar
 * unzip -l gradleHelloWorld-0.1.jar
 *
 */
public class Application {
    public static void main(String... args) {
        User user = new User("John");
        System.out.println(user);
    }
}
